[plugins.git]
enabled = true

[plugins.git.config]
main_branch = "master"
default_remote = "origin"
protected_branches = [
    "master",
]

[plugins.github]
enabled = true

[plugins.github.config]
repo_owner = "masmovil"
repo_name = "titan-cli"
default_branch = "master"
default_reviewers = []
